### ISSUE TITLE
transfer learning

### ISSUE THREAD

**Issue by fatemeh1291374** [dedhiaparth98/capsule-network#1]
Thank you very very much for your good explanation for implementing the network and publishing the code. 

I want to use your model as a transfer learning on my personal database, that's why I have two questions for your service.
1) To better adjust the model on my data, which layers should I freeze and which should I retrain?
2)What features should my input data have so that I do not have a problem with the input's shape?

Thanks a lot.
Best regards

**Comment by dedhiaparth98** [comment]
First responding to Question 2:
- Assuming you are aware of the theory behind transfer learning, you should have dataset which is similar to MNIST. So if you have any other dataset containing number or maybe characters than yes you may be able to work with that. 
- Going a little more detail on the dataset, like MNIST, you input data should have the actual characters in white and the background in black. 
- Regarding the input shape, you should try to keep the dimensions to the size of the MNIST images [28, 28]

Responding to question 1:
- Now which layers to freeze is selected based on the data on which the model was trained vs the data in which you want to fine-tune the model on.
- Incase if the data is very similar, then you can train very less layers. My personal opinion would be to fine-tune both the capsule layers, and the reason would be that the capsule in the primary capsule trigger the capsules in the next layer. I don't have any basis for making this statement and is purely based on intuition and could defer from any other actual implementation.
- For reconstruction layer, I am not entirely sure. You could empirically try it out and see does reconstruction loss add any benefit to you training.

Also, I would like to know if you are able to gain any success by implementing the fine-tuning task. So let me know if things turn out the way you expected them to be.

Thanks, have a great day!

**Comment by fatemeh1291374** [comment]
Thank you very much for your complete and kind answers. 
I will definitely inform you if I succeed in this field. But the following link fine-tune the original model using x-ray images of the chest. You may be interested to take a look at it.

https://github.com/ShahinSHH/COVID-CAPS

Thanks, Best regards.
